projectTitle: "RNA_all"
root: /work/ldybov5s/rnaseq/second_run/drop_bam            # root directory of all output objects and tables
htmlOutputPath: /work/ldybov5s/rnaseq/second_run/drop_bam/html  # path for HTML rendered reports
indexWithFolderName: false # whether the root base name should be part of the index name

hpoFile: null  # if null, downloads it from webserver
sampleAnnotation: /work/ldybov5s/rnaseq/second_run/drop_bam/samplesheet_drop_rna_all.tsv # path to sample annotation (see documentation on how to create it)

geneAnnotation:
    ensembl: /work/ldybov5s/rnaseq/reference_genome_Ensembl/Homo_sapiens.GRCh38.113.gtf
genomeAssembly: GRCh38
genome:
    ensembl: /work/ldybov5s/rnaseq/reference_genome_Ensembl/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
    # You can define multiple reference genomes in yaml format, ncbi: path/to/ncbi, ucsc: path/to/ucsc
    # the keywords that define the path should be in the GENOME column of the sample annotation table

exportCounts:
    geneAnnotations:
        - ensembl

          
aberrantExpression:
    run: true
    groups:
        - all
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 0.05
    zScoreCutoff: 0
    genesToTest: ../drop_genes.txt
    maxTestedDimensionProportion: 3
    yieldSize: 2000000

aberrantSplicing:
    run: true
    groups:
        - all
    recount: false
    longRead: false
    keepNonStandardChrs: false
    filter: true
    minExpressionInOneSample: 20
    quantileMinExpression: 10
    minDeltaPsi: 0.05
    implementation: PCA
    padjCutoff: 0.1
    maxTestedDimensionProportion: 6
    genesToTest: null
    ### FRASER1 configuration
    # FRASER_version: "FRASER" 
    # deltaPsiCutoff : 0.3 
    # quantileForFiltering: 0.95 
    ### For FRASER2, use the follwing parameters instead of the 3 lines above:
    FRASER_version: "FRASER2"
    deltaPsiCutoff : 0.1
    quantileForFiltering: 0.75

mae:
    run: true
    groups:
        - wgs
    gatkIgnoreHeaderCheck: true
    padjCutoff: 0.05
    allelicRatioCutoff: 0.8
    addAF: true
    maxAF: 0.001
    maxVarFreqCohort: 0.05
    # VCF-BAM matching
    qcVcf: /work/ldybov5s/rnaseq/drop_data/Ensembl/qc_vcf_1000G_GRCh38.vcf.gz
    qcGroups:
      - wgs
    dnaRnaMatchCutoff: 0.85

rnaVariantCalling:
    run: false
    groups:
        - batch_0
    highQualityVCFs:
        - Data/Mills_and_1000G_gold_standard.indels.hg19.sites.chrPrefix.vcf.gz
        - Data/1000G_phase1.snps.high_confidence.hg19.sites.chrPrefix.vcf.gz
    dbSNP: Data/00-All.vcf.gz
    repeat_mask: Data/hg19_repeatMasker_sorted.chrPrefix.bed
    createSingleVCF: true
    addAF: true
    maxAF: 0.001
    maxVarFreqCohort: 0.05
    hcArgs: ""
    minAlt: 3
    yieldSize: 100000

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools
